### PR TITLE
Calling parent constructor correctly for 2017.10 / PHP7 compatibility 

### PR DESCRIPTION
**Pull request by pkamps**
It's a follow up of
ezsystems/ezpublish-legacy#1233

Currently ezfind will through a fatal error search for an object.

*Testing instructions*
- in the admin interface do a search that will return result entries
- without this patch it will result in a PHP fatal error
- with this patch it will just show the result objects and there is no PHP fatal error

### CODE REVIEW

**Comment by andrerom** [comment]
Is this or other cases common? Afaik @jeromegamez was adding some BC methods around, so maybe worth it if we add one for this issue as well.

**Comment by andrerom** [comment]
@pkamps I guess we might need to add bump in requirement for legacy >= 2017.10 with this change or similar to avoid issues for people getting this once we tag but on a older legacy. WDYT @emodric?

**Comment by emodric** [comment]
Might be wise, yes.

**Comment by peterkeung** [comment]
+1

**Comment by gggeek** [comment]
+1 with the change in requirements

**Comment by pkamps** [comment]
I assume that bump has to happen in the composer.json file in this extension?
I must admit that I don't have much experience with composer - maybe you can help me out here?

The composer.json requires the "ezsystems/ezpublish-legacy-installer" - but that's different to "ezsystems/ezpublish-legacy", right? So I'm not sure if it makes sense to require a min version for "ezsystems/ezpublish-legacy-installer" - or maybe we need to change the requirements all together?

**Comment by emodric** [comment]
Yoi can add a require for `ezsystems/ezpublish-legacy` in version `>=2017.10`. No need for removing the existing ones.

**Pull request merged**
