### PR TITLE
Fix: EZP-23878 No result when I found 1 location in several languages wi...

### PR DESCRIPTION
**Pull request by blankse**
...th multicore ezfind

JIRA: https://jira.ez.no/browse/EZP-23878

### CODE REVIEW

**Comment by andrerom** [comment]
+0,5, review ping @yannickroger @paulborgermans

**Comment by bdunogier** [comment]
+1

**Comment by yannickroger** [comment]
It seems that your fix prevents the code from breaking later, could you explain your fix a bit more ?

**Comment by blankse** [comment]
In this case the $localNodeIDList variable is an array with several of the same IDs.
```
array( 123, 123, 123)
```

The eZContentObjectTreeNode::fetch function gets only a node instead of a node list. (Line: https://github.com/blankse/ezfind/blob/patch-1/search/plugins/ezsolr/ezsolr.php#L1625)

The if-statement fails because the $localNodeIDList have more than one elements (Line: https://github.com/blankse/ezfind/blob/patch-1/search/plugins/ezsolr/ezsolr.php#L1627)

**Comment by yannickroger** [comment]
+1 then.
ping @paulborgermans

**Comment by blankse** [comment]
ping @paulborgermans

**Comment by blankse** [comment]
ping @paulborgermans

**Comment by paulborgermans** [comment]
+1, sorry for late review

**Comment by andrerom** [comment]
@blankse Could you provide some feedback to QA in the issue on how this is reproduced? Seems to need some more info :)

**Comment by pcardiga** [comment]
ping @blankse QA is unable to reproduce this issue. Can you please provide the steps to reproduce in the issue? Thanks

**Comment by rpmsauron** [comment]
@blankse, I'm Rui Silva from the QA team. We are trying to reproduce the issue with the description provided but the info there doesn't seem enough to know how to proceed with reproducing it.
Can you please describe onto further detail the steps taken to reproduce it?
Thanks.

**Comment by andrerom** [comment]
I don't think it helps contacting him once per day, if he is not answering he is probably busy.

@paulborgermans Do you happen to know how this can be reproduced?

**Pull request merged**
