### PR TITLE
EZP-24914: Disabled SearchMainLanguageOnly setting does not take Site…

### PR DESCRIPTION
**Pull request by blankse**
…LanguageList into account

JIRA: https://jira.ez.no/browse/EZP-24914

### CODE REVIEW

**Comment by edelaunay** [comment]
Hello,
I think it's not a good idea to include this patch, because if you do this, you cannot search object which are in other language (not listed in LanguageList) and has the checkbox "Use main language if no translation" checked.
If you had this patch, the case see in this issue https://jira.ez.no/browse/EZP-19201 is not correct.

**Comment by blankse** [comment]
How is it possible only search in the languages of the SiteLanguageList?

In the ezfeZPSolrQueryBuilder class is the same behavour: https://github.com/ezsystems/ezfind/blob/master/classes/ezfezpsolrquerybuilder.php#L543

**Comment by blankse** [comment]
Can you look on this old PR? I would need it. @andrerom @bdunogier @yannickroger

**Comment by andrerom** [comment]
unsure here, it seems it might be breaking how it behaves and has been behaving for a long time. maybe @paulborgermans remembers what the intention here is.

**Comment by blankse** [comment]
@andrerom Should we add a new INI Setting for this behaving? The comment in the INI describes exactly this behavior: https://github.com/ezsystems/ezfind/blob/master/settings/ezfind.ini#L42

**Pull request closed without merging**
