### PR TITLE
Gitignore phpstorm

### PR DESCRIPTION
**Pull request by gggeek**

### CODE REVIEW

**Comment by nicolas-bastien** [comment]
Hi @gggeek,

This is a IDE file, you should configure your git config global to exclude this so it's done once for all the project you can have on your conputer.

Here is a link the github documentation : https://help.github.com/articles/ignoring-files/

And by the way, would be great if you can make a PR with only the commit that concern your modification please, it will help us to have a clean history this is really important.

**Comment by gggeek** [comment]
Hello.
This gitignore file already contains exclusions for ide files (.project), I see no reason why it could not have one more.
I know that you can set up this exclusion as well in git environment config, but with the advent of vms and docker I nowadays find myself working on code on half a million different installs, and find managing the git config for each environment more of a chore than managing it per project...

**Comment by nicolas-bastien** [comment]
> This gitignore file already contains exclusions for ide files (.project)

Good point, we should remove it too. Thank you.

> find managing the git config for each environment more of a chore than managing it per project...

Just share your gitconfig like you can do with your .shh config with your container, this will allow you to commit from your container if you need with the same config as your computer.

I just have one more question, right now if you commit from your virtual environnement, how to you handle your git user.email and user.name ?

**Comment by gggeek** [comment]
@nicolas-bastien it don't want to make this a long discussion, but:
- having the IDE files in gitignore has no known negative side effects
- especially since we are not talking about having in there hundreds of IDE, just a couple
- so I see no point in your proposal, only (admittedly small) disadvantages.
- I do not think that you trying to force a specific git workflow/setup on other users is a good idea. Making life easier for contributors is something that ezsystems has historically been extremely poor at, and the fact that the community today is very small and that pull requests are very few should tell you something about where you have opportunity for improving.
- For the record: I don't always share .ssh configs with vms/containers: I use putty and ssh-agent. I also use different email/username in different projects, so I can not use a single .gitconfig

**Pull request closed without merging**
